### PR TITLE
Do not use default.stringsAsFactors() any more and fix pkgdown

### LINKED ISSUE #8: docu: add missing functions to "groups"
Running pkgdown::build_site() currently complains that there are missing functions listed in the [_pkgdown.yaml](https://github.com/KWB-R/kwb.utils/blob/7a342f72f0cf6039b204bfc96a25d4262aeff3b7/_pkgdown.yaml)

```
Writing 'reference/index.html'
 Topics missing from index: decode, .defaultIf, .guessSeparator.1, .guessSeparator.2, .isNetworkPath, .log, .logline, .logok, .logstart, .OStype, encode, findPartialDuplicates, isASCII, isDotOrDoubleDot, printable_chars, removeDuplicates, rowOrColumnwisePercentage
```

See: 
http://kwb-r.github.io/kwb.utils/dev/reference/index.html

### LINKED ISSUE #35: Fix warning 'default.stringAsFactors' is deprecated
https://github.com/KWB-R/kwb.utils/runs/6625485980?check_suite_focus=true

Screenshot_2022-05-27-14-46-56-003_com android chrome

### PR DESCRIPTION
**Pull request by hsonne**
as this function is deprecated

---
This change is [Reviewable](https://reviewable.io/reviews/kwb-r/kwb.utils/36)

### CODE REVIEW

**Comment by mrustl** [comment]
Only pkgdown (#8 ) still failing....

**Comment by mrustl** [comment]
Maybe you can fix #8 also?

**Comment by mrustl** [comment]
See Herr:
https://github.com/KWB-R/kwb.utils/runs/6632021313?check_suite_focus=true

**Comment by hsonne** [comment]
Thanks @mrustl, everything fixed now.

**Pull request merged**
